# Generated by Django 2.2.17 on 2021-03-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210223_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='article',
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
