# Generated by Django 2.2.17 on 2021-03-10 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210310_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Article'),
        ),
    ]
